pluginManagement {
  repositories {
    mavenCentral()
    gradlePluginPortal()
    maven { url = 'https://repo.spring.io/release' }
    maven { url = 'https://repo.spring.io/milestone' }
    maven { url = 'https://repo.spring.io/snapshot' }
  }
}

dependencyResolutionManagement {
  repositories {
    mavenLocal()
    mavenCentral()
    maven { url = 'https://repo.spring.io/release' }
    maven { url = 'https://repo.spring.io/milestone' }
    maven { url = 'https://repo.spring.io/snapshot' }
  }
}

rootProject.name = 'spring-agent'

include 'spring-agent-core'
include 'spring-agent-persistence-jpa'
include 'spring-agent-persistence-mongodb'
include 'spring-agent-persistence-redis'
include 'spring-agent-tools-shell-kubernetes'
include 'spring-agent-tools-shell-docker'
include 'spring-agent-integration-feishu'
include 'spring-agent-events'
include 'spring-agent-integration-github'
include 'spring-agent-integration-gitlab'
include 'spring-agent-integration-grafana'
include 'spring-agent-rag-milvus'
include 'spring-agent-app'
include 'spring-agent-cli'
